name: Python application


env:
  AZURE_FUNCTIONAPP_NAME: 'senaclabazurefunctioninael'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  SECRETS_AZURE: '.'
  PYTHON_VERSION: '3.10'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Rodar testes
     # run: |
      #  pytest --maxfail=1 --disable-warnings -q > result.log

    
    - name: Criar Artefato
      uses: actions/upload-artifact@v3
      with:
        name: python-publish-app-artifact
        path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download do artefato da tarefa de build
      uses: actions/download-artifact@v3
      with:
        name: python-publish-app-artifact
        path: ./artifact

    - name: fazer Deploy para o Azure
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ./artifact/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
