name: Python application


env:
  AZURE_FUNCTIONAPP_NAME: 'senaclabazurefunctioninael'
  SECRETS_AZURE: '.'
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q > result.log

    
    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-publish-app-artifact
        path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download do artefato da tarefa de build anterior
      uses: actions/download-artifact@v3
      with:
        name: python-publish-app-artifact
        path: ./artifact

    - name: fazer Deploy para o Azure
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.SECRETS_AZURE }}
        publish-profile: ${{ secrets.SECRETS_AZURE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
