name: Python application build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests  # Onde 'tests' é o diretório dos testes

      - name: Create staging directory and copy distribution files
        run: |
          mkdir -p staging
          cp -r dist/* staging/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python Package
          path: staging/
