# .github/workflows/python-app.yml

name: Python CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checando o código
      uses: actions/checkout@v2  

    - name: Configurar o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Rodar testes
      run: |
        pytest 
