name: Python application build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code using flake8
      - name: Run flake8 linting
        run: |
          pip install flake8
          flake8 .

      # Run tests (assuming pytest is used)
      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

      # Create staging directory and copy distribution files
      - name: Create staging directory and copy distribution files
        run: |
          mkdir -p staging
          cp -r dist/* staging/

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python Package
          path: staging/
