# .github/workflows/python-app.yml

name: Python CI

on:
  push:
    branches:
      - main  # Aciona o workflow quando há um push para a branch "main"
  pull_request:
    branches:
      - main  # Aciona o workflow quando há um PR para a branch "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu para executar o CI

    steps:
    - name: Checando o código
      uses: actions/checkout@v2  # Faz o checkout do código para o ambiente

    - name: Configurar o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ou qualquer versão do Python que você preferir

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do arquivo requirements.txt

    - name: Rodar testes
      run: |
        pytest  # Executa os testes usando o pytest
